# -*- coding: utf-8 -*-
"""NinaPro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dhiaTnmYAIe3RdWV2DzOnmpxjTvegjg
"""

r"""
DATASET (NinaPro DB3 instructions + direct subject downloads):
https://ninapro.hevs.ch/instructions/DB3.html

PAPER 1 (Zhang 2025 - Broad Learning System on DB3, PubMed entry + DOI link to publisher):
https://pubmed.ncbi.nlm.nih.gov/40639397/
DOI: https://doi.org/10.1088/2057-1976/adee28

PAPER 2 (Niu 2024 - Improved DenseNet + STFT, uses DB3, Open Access, Heliyon):
https://www.sciencedirect.com/science/article/pii/S2405844024027944
DOI: https://doi.org/10.1016/j.heliyon.2024.e26763

PAPER 4 (Ovadia 2024 - ROCKET-based sEMG classification, Open Access on PMC):
https://pmc.ncbi.nlm.nih.gov/articles/PMC10876538/
"""

!pip install -q sktime scikit-learn

import numpy as np
import time
import os, glob
from scipy.io import loadmat
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix
from sklearn.linear_model import RidgeClassifier
from sktime.transformations.panel.rocket import MiniRocketMultivariate

#Step 1. Metrics Function
def compute_metrics(y_true, y_pred, label=""):
    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true, y_pred,
        average="macro",
        zero_division=0
    )
    cm = confusion_matrix(y_true, y_pred)

    print(f"\n=== METRICS: {label} ===")
    print(f"Accuracy:        {acc:.4f}")
    print(f"Macro Precision: {prec:.4f}")
    print(f"Macro Recall:    {rec:.4f}")
    print(f"Macro F1:        {f1:.4f}")
    print("Confusion matrix shape:", cm.shape)

    return {
        "accuracy": acc,
        "macro_precision": prec,
        "macro_recall": rec,
        "macro_f1": f1,
        "confusion_matrix": cm,
        "n_classes": len(np.unique(y_true)),
    }

# Step 2: Mount Google Drive (RUN FIRST)
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

# Step 3: Dataset path check
BASE_SUBJECTS = "/content/drive/MyDrive/ninapro_db3/subjects"

print("Base exists?", os.path.exists(BASE_SUBJECTS))
print("Subjects:", sorted(os.listdir(BASE_SUBJECTS))[:12])

# STEP 4: Load ONE subject (s1)

BASE_SUBJECTS = "/content/drive/MyDrive/ninapro_db3/subjects"

def load_subject_exercises_with_rep(subject_id="s1", base=BASE_SUBJECTS):
    folder = os.path.join(base, subject_id, f"DB3_{subject_id}")
    mat_files = sorted(glob.glob(os.path.join(folder, "*.mat")))

    emg_list, y_list, rep_list = [], [], []

    for fp in mat_files:
        m = loadmat(fp)
        emg_list.append(m["emg"].astype(np.float32))
        y_list.append(m["restimulus"].reshape(-1).astype(np.int32))
        rep_list.append(m["rerepetition"].reshape(-1).astype(np.int32))

    X = np.vstack(emg_list)
    y = np.concatenate(y_list)
    rep = np.concatenate(rep_list)

    return X, y, rep

X_s1, y_s1, rep_s1 = load_subject_exercises_with_rep("s1")

print("Shapes:", X_s1.shape, y_s1.shape, rep_s1.shape)
print("Label range:", y_s1.min(), "to", y_s1.max())
print("Unique labels:", len(np.unique(y_s1)))
print("Unique repetitions:", np.unique(rep_s1))

# STEP 5: Window subject s1

def window_emg_by_repetition(
    X, y, rep,
    fs=2000,
    win_ms=150,
    overlap=0.5
):
    win_len = int(fs * win_ms / 1000)      # 300 samples
    step = int(win_len * (1 - overlap))    # 150 step

    Xw, yw = [], []

    for r in np.unique(rep):
        idx = np.where(rep == r)[0]
        if len(idx) < win_len:
            continue

        Xr = X[idx]
        yr = y[idx]

        for start in range(0, len(Xr) - win_len + 1, step):
            end = start + win_len
            x_win = Xr[start:end].T               # (12, 300)
            label = yr[start + win_len // 2]      # center label

            Xw.append(x_win.astype(np.float32))
            yw.append(int(label))

    return np.stack(Xw), np.array(yw, dtype=np.int32)

# Window using repetition-aware windowing
Xw_s1, yw_s1 = window_emg_by_repetition(
    X_s1, y_s1, rep_s1,
    win_ms=150,
    overlap=0.5
)

print("Windowed shapes:", Xw_s1.shape, yw_s1.shape)
print("Window label range:", yw_s1.min(), "to", yw_s1.max())
print("Unique window labels:", len(np.unique(yw_s1)))

labels, counts = np.unique(yw_s1, return_counts=True)
print("Top 10 class counts:", list(zip(labels[:10], counts[:10])))

# Remove REST (label 0)
mask = (yw_s1 != 0)

Xw_nr = Xw_s1[mask]
yw_nr = yw_s1[mask]

print("No-rest shapes:", Xw_nr.shape, yw_nr.shape)
print("Unique labels (no rest):", len(np.unique(yw_nr)))
print("Label range:", yw_nr.min(), "to", yw_nr.max())

from sklearn.model_selection import train_test_split
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(
    Xw_nr,
    yw_nr,
    test_size=0.2,
    random_state=42,
    stratify=yw_nr
)

print("Train:", X_train.shape, y_train.shape)
print("Test :", X_test.shape, y_test.shape)
print("Train unique labels:", len(np.unique(y_train)))
print("Test unique labels :", len(np.unique(y_test)))

# STEP 6 — MiniROCKET + Ridge (NO-REST, s1)
import time
from sktime.transformations.panel.rocket import MiniRocketMultivariate
from sklearn.linear_model import RidgeClassifier

rocket = MiniRocketMultivariate(random_state=42)

t0 = time.time()
X_train_feat = rocket.fit_transform(X_train)
X_test_feat  = rocket.transform(X_test)
feat_time = time.time() - t0

clf = RidgeClassifier()

t0 = time.time()
clf.fit(X_train_feat, y_train)
train_time = time.time() - t0

t0 = time.time()
y_pred = clf.predict(X_test_feat)
infer_time = time.time() - t0

metrics_s1 = compute_metrics(
    y_test,
    y_pred,
    label="s1 | no-rest | repetition-aware | MiniROCKET"
)

print(f"Feature time:    {feat_time:.2f}s")
print(f"Train time:      {train_time:.2f}s")
print(f"Inference time:  {infer_time:.2f}s")

### Baseline A
import numpy as np

labels, counts = np.unique(yw_nr, return_counts=True)

summary = {
    "subject": "s1",
    "windowing": "150 ms, 50% overlap, repetition-aware",
    "rest_removed": True,
    "n_windows": len(yw_nr),
    "n_classes": len(labels),
    "min_samples_per_class": int(counts.min()),
    "max_samples_per_class": int(counts.max()),
    "model": "MiniROCKET + Ridge",
    "accuracy": 0.8587,
    "macro_f1": 0.8602,
}

summary

### ====LOSO====

# LOSO STEP 1: Subject-wise windowed datasets

import numpy as np

SUBJECTS = [f"s{i}" for i in range(1, 12)]

loso_data = {}   # RESET and rebuild

for sid in SUBJECTS:
    print(f"\nProcessing {sid}...")

    # 1) load raw EMG + labels + repetitions
    X_raw, y_raw, rep_raw = load_subject_exercises_with_rep(sid)

    # 2) repetition-aware windowing
    Xw, yw = window_emg_by_repetition(
        X_raw, y_raw, rep_raw,
        win_ms=150,
        overlap=0.5
    )

    # 3) remove REST (label 0)
    mask = (yw != 0)
    Xw = Xw[mask]
    yw = yw[mask]

    # 4) store
    loso_data[sid] = {
        "X": Xw,
        "y": yw
    }

    # 5) sanity checks
    labels, counts = np.unique(yw, return_counts=True)
    print(f"  Windows: {Xw.shape[0]}")
    print(f"  Classes: {len(labels)}")
    print(f"  Min samples/class: {counts.min()}")
    print(f"  Max samples/class: {counts.max()}")

print(loso_data.keys())
print(loso_data["s1"]["X"].shape, loso_data["s1"]["y"].shape)

# STEP 2A — choose LOSO test subject

import numpy as np

TEST_SUBJECT = "s1"

# 1) Test data
X_test = loso_data[TEST_SUBJECT]["X"]
y_test = loso_data[TEST_SUBJECT]["y"]

# 2) Train data = all other subjects
X_train_list = []
y_train_list = []

for sid, data in loso_data.items():
    if sid == TEST_SUBJECT:
        continue
    X_train_list.append(data["X"])
    y_train_list.append(data["y"])

X_train = np.concatenate(X_train_list, axis=0)
y_train = np.concatenate(y_train_list, axis=0)

# 3) Sanity checks
print(f"LOSO TEST SUBJECT: {TEST_SUBJECT}\n")

print("TRAIN:")
print("  Shape:", X_train.shape, y_train.shape)
print("  Classes:", len(np.unique(y_train)))
print("  Label range:", y_train.min(), "to", y_train.max())

print("\nTEST:")
print("  Shape:", X_test.shape, y_test.shape)
print("  Classes:", len(np.unique(y_test)))
print("  Label range:", y_test.min(), "to", y_test.max())

# 4) Class leakage check
missing = set(np.unique(y_test)) - set(np.unique(y_train))
print("\nClasses in TEST but not in TRAIN:", missing)

# LOSO STEP 2B: Subsample TRAIN windows (memory-safe)

import numpy as np

MAX_TRAIN_WINDOWS = 15000   # safe for Colab (you can try 75000 later)

rng = np.random.default_rng(42)

n_train = X_train.shape[0]

if n_train > MAX_TRAIN_WINDOWS:
    idx = rng.choice(n_train, size=MAX_TRAIN_WINDOWS, replace=False)
    X_train_sub = X_train[idx]
    y_train_sub = y_train[idx]
else:
    X_train_sub = X_train
    y_train_sub = y_train

print("Original TRAIN:", X_train.shape)
print("Subsampled TRAIN:", X_train_sub.shape)
print("TEST (unchanged):", X_test.shape)

from sktime.transformations.panel.rocket import MiniRocketMultivariate
from sklearn.linear_model import RidgeClassifier
import time

print("X_train_sub exists?", "X_train_sub" in globals())
print("y_train_sub exists?", "y_train_sub" in globals())
print("X_test exists?", "X_test" in globals())
print("y_test exists?", "y_test" in globals())

print("X_train_sub:", X_train_sub.shape)
print("y_train_sub:", y_train_sub.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train_sub = X_train_sub.astype("float32")
X_test = X_test.astype("float32")

print(X_train_sub.dtype, X_test.dtype)

# LOSO STEP 2C: MiniROCKET feature extraction

from sktime.transformations.panel.rocket import MiniRocketMultivariate
import time

rocket = MiniRocketMultivariate(
    random_state=42,
    num_kernels=5000
)

t0 = time.time()

# FIT on TRAIN ONLY
X_train_feat = rocket.fit_transform(X_train_sub)

# TRANSFORM test (NO fit)
X_test_feat = rocket.transform(X_test)

feat_time = time.time() - t0

print("MiniROCKET DONE")
print("Train features:", X_train_feat.shape)
print("Test features :", X_test_feat.shape)
print(f"Feature extraction time: {feat_time:.2f}s")

# Step 3 A from sklearn.linear_model import RidgeClassifier
import time

from sklearn.linear_model import RidgeClassifier
import time

clf = RidgeClassifier(alpha=100.0)  # stronger regularization

t0 = time.time()
clf.fit(X_train_feat, y_train_sub)
train_time = time.time() - t0

t0 = time.time()
y_pred = clf.predict(X_test_feat)
infer_time = time.time() - t0

print("Ridge DONE (SAFE)")
print(f"Train time: {train_time:.2f}s")
print(f"Inference time: {infer_time:.2f}s")

# STEP 3B — Metrics function call
metrics_loso_s1 = compute_metrics(
    y_test,
    y_pred,
    label="LOSO | test=s1 | MiniROCKET (5k kernels)"
)

# STEP 3C — Store results cleanly (for report / table)
metrics_loso_s1.update({
    "test_subject": "s1",
    "n_train_windows": X_train_sub.shape[0],
    "n_test_windows": X_test.shape[0],
    "model": "MiniROCKET + Ridge",
})

metrics_loso_s1

loso_results = []

loso_results.append(metrics_loso_s1)

len(loso_results), loso_results[0]["test_subject"]

from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix
import numpy as np

def compute_metrics(y_true, y_pred, label=""):
    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true, y_pred,
        average="macro",
        zero_division=0
    )
    cm = confusion_matrix(y_true, y_pred)

    print(f"\n=== METRICS: {label} ===")
    print(f"Accuracy:        {acc:.4f}")
    print(f"Macro Precision: {prec:.4f}")
    print(f"Macro Recall:    {rec:.4f}")
    print(f"Macro F1:        {f1:.4f}")
    print("Confusion matrix shape:", cm.shape)

    return {
        "accuracy": acc,
        "macro_precision": prec,
        "macro_recall": rec,
        "macro_f1": f1,
        "confusion_matrix": cm,
        "n_classes": len(np.unique(y_true)),
    }

# MUST be run before LOSO loop
print(loso_data.keys())

print("loso_data exists?", "loso_data" in globals())
print("compute_metrics exists?", "compute_metrics" in globals())

# Step 4: LOSO into a LOOP
from sktime.transformations.panel.rocket import MiniRocketMultivariate
from sklearn.linear_model import RidgeClassifier
import numpy as np
import time
import gc   # garbage collection

loso_results = []

MAX_TRAIN_WINDOWS = 3000   # 🔴 keep this small for stability
rng = np.random.default_rng(42)

for TEST_SUBJECT in sorted(loso_data.keys()):

    print(f"\n==============================")
    print(f"LOSO TEST SUBJECT: {TEST_SUBJECT}")
    print(f"==============================")

    # ---------- TEST ----------
    X_test = loso_data[TEST_SUBJECT]["X"].astype("float32")
    y_test = loso_data[TEST_SUBJECT]["y"]

    # ---------- TRAIN (SUBSAMPLED PER SUBJECT) ----------
    X_train_list = []
    y_train_list = []

    for sid, data in loso_data.items():
        if sid == TEST_SUBJECT:
            continue

        Xs = data["X"]
        ys = data["y"]

        # subsample EACH subject before concatenation
        if len(Xs) > MAX_TRAIN_WINDOWS // (len(loso_data) - 1):
            idx = rng.choice(
                len(Xs),
                size=MAX_TRAIN_WINDOWS // (len(loso_data) - 1),
                replace=False
            )
            Xs = Xs[idx]
            ys = ys[idx]

        X_train_list.append(Xs)
        y_train_list.append(ys)

    X_train = np.concatenate(X_train_list).astype("float32")
    y_train = np.concatenate(y_train_list)

    print("Train:", X_train.shape, "Test:", X_test.shape)

    # ---------- MiniROCKET ----------
    rocket = MiniRocketMultivariate(random_state=42)

    t0 = time.time()
    X_train_feat = rocket.fit_transform(X_train)
    X_test_feat = rocket.transform(X_test)
    feat_time = time.time() - t0

    # ---------- Ridge ----------
    clf = RidgeClassifier(alpha=10.0)

    t0 = time.time()
    clf.fit(X_train_feat, y_train)
    train_time = time.time() - t0

    t0 = time.time()
    y_pred = clf.predict(X_test_feat)
    infer_time = time.time() - t0

    # ---------- Metrics ----------
    metrics = compute_metrics(
        y_test,
        y_pred,
        label=f"LOSO | test={TEST_SUBJECT}"
    )

    metrics.update({
        "test_subject": TEST_SUBJECT,
        "n_train_windows": len(y_train),
        "n_test_windows": len(y_test),
        "feature_time": feat_time,
        "train_time": train_time,
        "infer_time": infer_time,
        "model": "MiniROCKET + Ridge",
    })

    loso_results.append(metrics)

    # ---------- MEMORY CLEANUP ----------
    del X_train, y_train, X_train_feat, X_test_feat, rocket, clf
    gc.collect()

import pandas as pd

df_loso = pd.DataFrame(loso_results)
df_loso[[
    "test_subject",
    "accuracy",
    "macro_f1",
    "n_train_windows",
    "n_test_windows"
]]

df_loso[["accuracy", "macro_f1"]].describe()

# Step 4: LOSO into a LOOP
from sktime.transformations.panel.rocket import MiniRocketMultivariate
from sklearn.linear_model import RidgeClassifier
import numpy as np
import time
import gc   # garbage collection

loso_results = []

MAX_TRAIN_WINDOWS = 8000   # 🔴 keep this small for stability
rng = np.random.default_rng(42)

for TEST_SUBJECT in sorted(loso_data.keys()):

    print(f"\n==============================")
    print(f"LOSO TEST SUBJECT: {TEST_SUBJECT}")
    print(f"==============================")

    # ---------- TEST ----------
    X_test = loso_data[TEST_SUBJECT]["X"].astype("float32")
    y_test = loso_data[TEST_SUBJECT]["y"]

    # ---------- TRAIN (SUBSAMPLED PER SUBJECT) ----------
    X_train_list = []
    y_train_list = []

    for sid, data in loso_data.items():
        if sid == TEST_SUBJECT:
            continue

        Xs = data["X"]
        ys = data["y"]

        # subsample EACH subject before concatenation
        if len(Xs) > MAX_TRAIN_WINDOWS // (len(loso_data) - 1):
            idx = rng.choice(
                len(Xs),
                size=MAX_TRAIN_WINDOWS // (len(loso_data) - 1),
                replace=False
            )
            Xs = Xs[idx]
            ys = ys[idx]

        X_train_list.append(Xs)
        y_train_list.append(ys)

    X_train = np.concatenate(X_train_list).astype("float32")
    y_train = np.concatenate(y_train_list)

    print("Train:", X_train.shape, "Test:", X_test.shape)

    # ---------- MiniROCKET ----------
    rocket = MiniRocketMultivariate(random_state=42)

    t0 = time.time()
    X_train_feat = rocket.fit_transform(X_train)
    X_test_feat = rocket.transform(X_test)
    feat_time = time.time() - t0

    # ---------- Ridge ----------
    clf = RidgeClassifier(alpha=10.0)

    t0 = time.time()
    clf.fit(X_train_feat, y_train)
    train_time = time.time() - t0

    t0 = time.time()
    y_pred = clf.predict(X_test_feat)
    infer_time = time.time() - t0

    # ---------- Metrics ----------
    metrics = compute_metrics(
        y_test,
        y_pred,
        label=f"LOSO | test={TEST_SUBJECT}"
    )

    metrics.update({
        "test_subject": TEST_SUBJECT,
        "n_train_windows": len(y_train),
        "n_test_windows": len(y_test),
        "feature_time": feat_time,
        "train_time": train_time,
        "infer_time": infer_time,
        "model": "MiniROCKET + Ridge",
    })

    loso_results.append(metrics)

    # ---------- MEMORY CLEANUP ----------
    del X_train, y_train, X_train_feat, X_test_feat, rocket, clf
    gc.collect()

import pandas as pd

df_loso = pd.DataFrame(loso_results)

df_loso = df_loso[[
    "test_subject",
    "accuracy",
    "macro_f1",
    "n_train_windows",
    "n_test_windows",
]]

df_loso

df_loso.describe()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.bar(df_loso["test_subject"], df_loso["accuracy"])
plt.axhline(1/49, color="red", linestyle="--", label="Chance")
plt.ylabel("Accuracy")
plt.xlabel("Test subject")
plt.title("LOSO Accuracy per Subject (MiniROCKET + Ridge)")
plt.legend()
plt.show()